# Generated by Django 2.2.4 on 2019-09-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
