# Generated by Django 2.2.4 on 2019-09-01 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posttuto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('head1', models.TextField()),
                ('content1', models.TextField()),
                ('head2', models.TextField()),
                ('content2', models.TextField()),
                ('head3', models.TextField()),
                ('content3', models.TextField()),
                ('head4', models.TextField()),
                ('content4', models.TextField()),
                ('head5', models.TextField()),
                ('content5', models.TextField()),
                ('head6', models.TextField()),
                ('content6', models.TextField()),
                ('head7', models.TextField()),
                ('content7', models.TextField()),
                ('head8', models.TextField()),
                ('content8', models.TextField()),
                ('head9', models.TextField()),
                ('content9', models.TextField()),
                ('head10', models.TextField()),
                ('content10', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
