# Generated by Django 2.2.4 on 2019-09-01 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_photo_posttuto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttuto',
            name='author',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Posttuto',
        ),
    ]
