# Generated by Django 2.2.4 on 2019-09-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190901_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttuto',
            name='content1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='content9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file10',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file5',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file6',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file7',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file8',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='file9',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttuto',
            name='head9',
            field=models.TextField(blank=True, null=True),
        ),
    ]
