# Generated by Django 2.2.4 on 2019-09-02 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20190902_0840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('head1', models.TextField(blank=True, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('head2', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('head3', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('head4', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('head5', models.TextField(blank=True, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
                ('head6', models.TextField(blank=True, null=True)),
                ('content6', models.TextField(blank=True, null=True)),
                ('head7', models.TextField(blank=True, null=True)),
                ('content7', models.TextField(blank=True, null=True)),
                ('head8', models.TextField(blank=True, null=True)),
                ('content8', models.TextField(blank=True, null=True)),
                ('head9', models.TextField(blank=True, null=True)),
                ('content9', models.TextField(blank=True, null=True)),
                ('head10', models.TextField(blank=True, null=True)),
                ('content10', models.TextField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Posttuto',
        ),
    ]
