# Generated by Django 2.2.4 on 2019-09-02 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_imagesall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images10',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images2',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images3',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images4',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images5',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images6',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images7',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images8',
            name='post',
        ),
        migrations.RemoveField(
            model_name='images9',
            name='post',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
        migrations.DeleteModel(
            name='Images10',
        ),
        migrations.DeleteModel(
            name='Images2',
        ),
        migrations.DeleteModel(
            name='Images3',
        ),
        migrations.DeleteModel(
            name='Images4',
        ),
        migrations.DeleteModel(
            name='Images5',
        ),
        migrations.DeleteModel(
            name='Images6',
        ),
        migrations.DeleteModel(
            name='Images7',
        ),
        migrations.DeleteModel(
            name='Images8',
        ),
        migrations.DeleteModel(
            name='Images9',
        ),
    ]
