# Generated by Django 2.2.4 on 2019-09-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20190902_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImagesAll',
            new_name='Images',
        ),
    ]
