# Generated by Django 2.2.4 on 2019-09-01 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190901_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
